export enum MutationTypes {
    SET_MENU_LIST = 'SET_MENU_LIST',
    SET_PERMIESSION = 'SET_PERMIESSION',
    SET_MENU_GROUP = "SET_MENU_GROUP",
    SET_VIEW_ROUTES = "SET_VIEW_ROUTES",
    COLLAPSE_MENU = "COLLAPSE_MENU"
}
