# CMake generated Testfile for 
# Source directory: /Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio
# Build directory: /Users/virtualman/Downloads/MySource/opencv-4.3.0/release/modules/videoio
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_videoio "/Users/virtualman/Downloads/MySource/opencv-4.3.0/release/bin/opencv_test_videoio" "--gtest_output=xml:opencv_test_videoio.xml")
set_tests_properties(opencv_test_videoio PROPERTIES  LABELS "Main;opencv_videoio;Accuracy" WORKING_DIRECTORY "/Users/virtualman/Downloads/MySource/opencv-4.3.0/release/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/virtualman/Downloads/MySource/opencv-4.3.0/cmake/OpenCVUtils.cmake;1640;add_test;/Users/virtualman/Downloads/MySource/opencv-4.3.0/cmake/OpenCVModule.cmake;1309;ocv_add_test_from_target;/Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio/CMakeLists.txt;191;ocv_add_accuracy_tests;/Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio/CMakeLists.txt;0;")
add_test(opencv_perf_videoio "/Users/virtualman/Downloads/MySource/opencv-4.3.0/release/bin/opencv_perf_videoio" "--gtest_output=xml:opencv_perf_videoio.xml")
set_tests_properties(opencv_perf_videoio PROPERTIES  LABELS "Main;opencv_videoio;Performance" WORKING_DIRECTORY "/Users/virtualman/Downloads/MySource/opencv-4.3.0/release/test-reports/performance" _BACKTRACE_TRIPLES "/Users/virtualman/Downloads/MySource/opencv-4.3.0/cmake/OpenCVUtils.cmake;1640;add_test;/Users/virtualman/Downloads/MySource/opencv-4.3.0/cmake/OpenCVModule.cmake;1211;ocv_add_test_from_target;/Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio/CMakeLists.txt;192;ocv_add_perf_tests;/Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio/CMakeLists.txt;0;")
add_test(opencv_sanity_videoio "/Users/virtualman/Downloads/MySource/opencv-4.3.0/release/bin/opencv_perf_videoio" "--gtest_output=xml:opencv_perf_videoio.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_videoio PROPERTIES  LABELS "Main;opencv_videoio;Sanity" WORKING_DIRECTORY "/Users/virtualman/Downloads/MySource/opencv-4.3.0/release/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/virtualman/Downloads/MySource/opencv-4.3.0/cmake/OpenCVUtils.cmake;1640;add_test;/Users/virtualman/Downloads/MySource/opencv-4.3.0/cmake/OpenCVModule.cmake;1212;ocv_add_test_from_target;/Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio/CMakeLists.txt;192;ocv_add_perf_tests;/Users/virtualman/Downloads/MySource/opencv-4.3.0/modules/videoio/CMakeLists.txt;0;")
