spring:
  profiles:
    active: prd
#debug: true
#
#logging:
#  level:
#    root: info
#  file: D:/my_software_engineering/my_java_project/my_idea_project/MySpringInitializr/myspringbootyml.log
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password:
#
#
#mall:
#  config:
#    name: 爱美商城
#    description: 这是一个化妆品特卖网站
#    hot-sales: 20
#    show-advert: true