############################################################
#
# web访问端口号  约定：8080
#
############################################################
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
