apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  - protocol: TCP
    port: 15672
    targetPort: 15672