server:
  port: 20003


spring:
  application:
    name: config-server
  ## rabbitMQ用于Bus推送 生产环境
  rabbitmq:
    host: 10.34.96.3
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        overrides:
          # 属性重载 也就是把属性覆盖掉吧
          test: mytest
        git:
          uri: https://github.com/OSrcD/foodie-cloud-config.git
          force-pull: true
          # 在主目录创建不同的文件夹 管理配置文件
          # 将配置文件放到接入方服务名称对应文件夹下
          search-paths: '{application}'
          # username:
          # password:
# 本地环境
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:20000/eureka/
# 生产环境
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.34.96.3:20000/eureka/
  # 生产环境
  # 使用 ip 地址形式注册 希望以ip地址是形式在Eureka里面进行互通
  instance:
    # IP 地址部署默认容器的 ip 地址 容器会起一个自己内部的私有ip地址
    # 这个ip地址外网不能访问的 所以我们要指定服务器的地址 端口还是容器的端口
    # 10.34.96.3:20003
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: 10.34.96.3
    prefer-ip-address: true

## 开启所有actuator-endpoint
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always