server:
  port: 10006

spring:
  application:
    name: foodie-auth-service
  redis:
    database: 0
    host: 192.168.245.138
    port: 6379
    password: imooc

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    user:
      name: gitee
      password: gitee
      roles: ADMIN
